1

diff --git a/0x01-shell_permissions/3-new_owner b/0x01-shell_permissions/3-new_owner
--- a/0x01-shell_permissions/3-new_owner
+++ b/0x01-shell_permissions/3-new_owner
@@ -1,2 +1,9 @@
 #!/bin/bash
-sudo chown betty hello
+sudo chown betty hello >/dev/null 2>&1
+if [ $? -eq 0 ]; then
+    echo "Successfully changed owner to betty"
+else
+    echo "Failed to change owner to betty"
+fi
+echo "New owner:"
+ls -l hello | awk '{print $3}'
